version: '3.2'

volumes:
  tmp-data:
  redis-data:

services:
  app:
    image: golang:1.13-stretch
    working_dir: /src
    command: ./golang-developer-test-task
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      HOME: /tmp
      GOPATH: /tmp
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - .:/src:cached
      - tmp-data:/tmp:cached
    depends_on:
      - redis
    networks:
      - test_app

  redis:
    image: redis:5.0.7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data:cached
    networks:
      - test_app

networks:
  test_app:
